variables:
- name: ReleaseEnvironmentName
  value: dev-draft
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: cosmosDBCollectionName
  value: shared-content-draft
- name: triagetoolDbCollectionName
  value: triagetool-draft
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Triagetool
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-triagetool-draft
- name: contentUrl
  value: $(ContentApiDraftAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-dev-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/triagetool-draft
- name: apiName
  value: triagetool-draft
- name: apiId
  value: composite-ui-triagetool-draft
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-dev-draft-app-triagetool
- name: SubscriptionSettingsFilterIncludeEventTypes3
  value: draft-discarded
- name: SubscriptionSettingsFilterIncludeEventTypes4
  value: unpublished
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
  value: 2c9da1b3-3529-4834-afc9-9cd741e59788
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values1
  value: /content/page/
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values2
  value: /content/triagetooloption/
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values3
  value: /content/triagetoolfilter/
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values4
  value: /content/applicationview/
- name: EnableAzureMonitorAlerting
  value: true
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: clientAffinity
  value: false
- name: appDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75