variables:
- name: ReleaseEnvironmentName
  value: lab
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Triagetool
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-triagetool
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: apiName
  value: triagetool
- name: apiId
  value: composite-ui-triagetool
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-lab-app-triagetool
- name: EnableAzureMonitorAlerting
  value: true
- name: appDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: contentMode
  value: PUBLISHED
- name: Expiry
  value: 4