variables:
- name: ReleaseEnvironmentName
  value: pp-draft
- name: AppServiceName
  value: $(WebAppPrefix)-as-ver2
- name: AppServicePlanSuffix
  value: -migrated
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Triagetool
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-triagetool-draft
- name: contentUrl
  value: $(ContentApiDraftAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-pp-api-eventgridsubscriptions-fa-ver2.$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/triagetool-draft
- name: apiName
  value: triagetool-draft
- name: apiId
  value: composite-ui-triagetool-draft
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-pp-draft-app-triagetool
- name: EnableAzureMonitorAlerting
  value: true
- name: appDatabaseThroughput
  value: 2500
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: contentMode
  value: DRAFT
- name: Expiry
  value: 4