variables:
- name: ReleaseEnvironmentName
  value: pp
- name: AppServiceName
  value: $(WebAppPrefix)-as-ver2
- name: AppServicePlanSuffix
  value: -migrated
- name: cosmosDBCollectionName
  value: shared-content
- name: triagetoolDbCollectionName
  value: triagetool
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Triagetool
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-triagetool
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-pp-api-eventgridsubscriptions-fa-ver2.$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/triagetool
- name: apiName
  value: triagetool
- name: apiId
  value: composite-ui-triagetool
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-pp-app-triagetool
- name: EnableAzureMonitorAlerting
  value: true
- name: clientAffinity
  value: false
- name: appDatabaseThroughput
  value: 2500
- name: ExceptionCountThreshold
  value: 10
- name: contentMode
  value: PUBLISHED
- name: Expiry
  value: 4