variables:
- name: ReleaseEnvironmentName
  value: prd-draft
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Triagetool
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-triagetool-draft
- name: contentUrl
  value: $(ContentApiDraftAddress)/api/execute
- name: apiName
  value: triagetool-draft
- name: apiId
  value: composite-ui-triagetool-draft
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-prd-draft-app-triagetool
- name: EnableAzureMonitorAlerting
  value: true
- name: appDatabaseThroughput
  value: 2500
- name: ExceptionCountThreshold
  value: 10
- name: contentMode
  value: DRAFT
- name: Expiry
  value: 4